### ISSUE TITLE
Code is not working

### ISSUE THREAD

**Issue by Muhandisbro** [YumikoKawaii/Multi-Robot-Systems-in-Warehouse-Simulation#1]
Hi thanks for this amazing project but i wanna tell you that the code is not working, can you plz tell me whats the error, many thanks and regard
error:
Unrecognized function or variable 'MultiRobotEnv'.

Error in Multi_robot_System_in_Warehouse (line 84)
env = MultiRobotEnv(numRobots);

**Comment by YumikoKawaii** [comment]
This project using mobile robotics simulation toolbox. You may not have the toolbox so you can't run the code

**Comment by Muhandisbro** [comment]
I have the toolbox sir

**Comment by YumikoKawaii** [comment]
Oh shj*t, god know, i don't know :v, pardon me :v

**Comment by Muhandisbro** [comment]
Haha, thanks!
